# Generated by Django 6.1.1 on 2026-09-14 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_app', '0003_document_error_message_document_processed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('index', models.PositiveIntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents_app.document')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('document', 'index')},
            },
        ),
    ]
