# Generated by Django 6.1.1 on 2026-09-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_app', '0004_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
