# Generated by Django 6.1.1 on 2026-09-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_app', '0005_chunk_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='embedded_txt',
            field=models.JSONField(null=True),
        ),
    ]
