# Generated by Django 6.1.1 on 2026-09-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_app', '0006_chunk_embedded_txt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='embedded_txt',
        ),
        migrations.AddField(
            model_name='chunk',
            name='embedding',
            field=models.JSONField(null=True),
        ),
    ]
